name: Deploy to Production 
 
on: 
  push: 
    branches: [ main ] 
  workflow_dispatch: 
 
jobs: 
  deploy: 
    runs-on: ubuntu-latest 
 
    steps: 
    - name: Deploy to server 
      uses: appleboy/ssh-action@v0.1.8 
      with: 
        host: ${{ secrets.HOST }} 
        username: ${{ secrets.USERNAME }} 
        password: ${{ secrets.PASSWORD }} 
        script: | 
          cd /var/www/frozenbot-project 
          git pull origin main 
          echo "Deployment completed!" 
